language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS=""
before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - sudo apt-get install ffmpeg
  - sudo apt-get -y update
  - sudo apt-get install -y mediainfo

script:
  - ffmpeg -version
  - mediainfo --version
  - mediainfo --Output=JSON tests/files/test.mp4
  - vendor/bin/phpunit tests
