language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - sudo apt-get install ffmpeg

script:
  - /usr/bin/ffmpeg -y -i /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test.mp4 -c:v libx264 -s:v 256x144 -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_list_size 0 -hls_time 5 -hls_allow_cache 1 -b:v 237k -maxrate 284k -hls_segment_filename /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_144p_%04d.ts /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_144p.m3u8 -s:v 426x240 -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_list_size 0 -hls_time 5 -hls_allow_cache 1 -b:v 292k -maxrate 350k -hls_segment_filename /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_240p_%04d.ts /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_240p.m3u8 -s:v 640x360 -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_list_size 0 -hls_time 5 -hls_allow_cache 1 -b:v 380k -maxrate 456k -hls_segment_filename /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_360p_%04d.ts -strict -2 /home/travis/build/aminyazdanpanah/PHP-FFmpeg-video-streaming/tests/files/test_360p.m3u8
  - vendor/bin/phpunit tests
